#!/usr/bin/with-contenv bash

function version_ge() { test "$(printf '%s\n' "$@" | sort -V | head -n 1)" == "$1"; }

required_beets_version="1.4.7"
beets_version=$(beet --version 2>/dev/null | grep ^beets | awk '{print $NF}')

if version_ge "$required_beets_version" "$beets_version" ; then
  echo "Running furiousgeorge/beets-alternative-mod installation of beets-alternatives"
  pip3 install --no-cache-dir -U beets-alternatives
fi
